name: MirrorBot Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   

jobs:
  build:
    runs-on: brock5555/vcom-dan

      - name: Set Git Configs & Secrets
        run: |
          ls
          python3 start.py
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      

      
      
